apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    m-app: vbserver
  name: vbserver-monitor
  namespace: default
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      m-app: vbserver