apiVersion: v1
kind: Pod
metadata:
  name: vbserver-one
  labels:
    app: vbserver-one
    m-app: vbserver
spec:
  nodeSelector:
    "kubernetes.io/os": windows
  containers:
  - name: vbserver-one
    image: jmaks.azurecr.io/vbserver:3.2
    ports:
    - containerPort: 9001
      name: telnet
    - containerPort: 9144
      name: metrics
  tolerations:
  - key: "os"
    operator: "Equal"
    value: "windows"
    effect: "NoSchedule"
---

apiVersion: v1
kind: Service
metadata:
  name: vbserver-one-lb
spec:
  type: LoadBalancer
  selector:
    app: vbserver-one
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001

---

apiVersion: v1
kind: Pod
metadata:
  name: vbserver-two
  labels:
    m-app: vbserver
    app: vbserver-two
spec:
  nodeSelector:
    "kubernetes.io/os": windows
  containers:
  - name: vbserver-two
    image: jmaks.azurecr.io/vbserver:3.2
    ports:
    - containerPort: 9001
      name: telnet
    - containerPort: 9144
      name: metrics
  tolerations:
  - key: "os"
    operator: "Equal"
    value: "windows"
    effect: "NoSchedule"
---

apiVersion: v1
kind: Service
metadata:
  name: vbserver-two-lb
spec:
  type: LoadBalancer
  selector:
    app: vbserver-two
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
---

apiVersion: v1
kind: Pod
metadata:
  name: vbserver-three
  labels:
    m-app: vbserver
    app: vbserver-three
    name: vbserver-three
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9144"
      prometheus.io/path: /metrics
spec:
  nodeSelector:
    "kubernetes.io/os": windows
  containers:
  - name: vbserver-three
    image: jmaks.azurecr.io/vbserver:3.2
    ports:
    - containerPort: 9001
      name: telnet
    - containerPort: 9144
      name: metrics
    readinessProbe:
      tcpSocket:
        port: 9001
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 9001
      initialDelaySeconds: 15
      periodSeconds: 20
  tolerations:
  - key: "os"
    operator: "Equal"
    value: "windows"
    effect: "NoSchedule"
---

apiVersion: v1
kind: Service
metadata:
  name: vbserver-three-lb
spec:
  type: LoadBalancer
  selector:
    app: vbserver-three
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001

