global:
  config_version: 3
input:
  type: file
  path: /temp/*.log
  fail_on_missing_logfile: false
  poll_interval: 5s
  readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
imports:
- type: grok_patterns
  dir: c:/grok/patterns
metrics:
- type: counter
  name: app_total_errors
  help: Total number of errors partitioned by error number.
  match: '%{TIMESTAMP_ISO8601} ERROR %{INT:errno} %{QS:source} %{QS:desription}'
  labels:
    error_number: '{{.errno}}'
    error_source: '{{.source}}'
    logfile: '{{base .logfile}}'
- type: counter
  name: app_messages_total
  help: Total number of info messages partitioned by name
  match: '%{TIMESTAMP_ISO8601} INFO %{USERNAME:name}: %{QS:data}'
  labels:
      user: '{{.name}}'
server:
  protocol: http
  port: 9144
