# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019
LABEL maintainer="https://github.com/jmservera"                                         `
    org.opencontainers.image.authors="https://github.com/jmservera"                     `
    org.opencontainers.image.url="[pending]"                                            `
    org.opencontainers.image.title="VB6 PoC"                                             `
    org.opencontainers.image.description="Windows container with a small VB6 PoC"  `
    org.opencontainers.image.source="https://github.com/jmservera/legacyvb6ink8s" 